### ISSUE TITLE
Create CI with update site

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-eclipse#2]
A CI that should produce an update site.

**Comment by JanKoehnlein** [comment]
Added a mvn build
Remaining tasks:
- [ ] copy web app to io.typefox.yang.diagram/diagram
- [ ] copy LSP to i.t.y.eclipse/language-server
- [ ] test the installation
- [ ] set up Jenkins to run gradle for the LSP, yarn for the diagram client and mvn for the eclipse integration

**Comment by JanKoehnlein** [comment]
Done. See http://services.typefox.io/open-source/jenkins/job/yang-eclipse/job/master/lastSuccessfulBuild/artifact/yang-eclipse/io.typefox.yang.eclipse.repository/target/repository/
